/**
 * Generate Day-1 morning/evening curriculum packs for 6 NER states (Assam already ships).
 * Run: node scripts/generate_ner_packs.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..', 'server', 'curriculum', 'packs');
const PUBLIC = path.join(__dirname, '..', 'public', 'curriculum', 'packs');

const WEEKDAY_EN = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
const WEEKDAY_HI = ['Ravivar', 'Somvar', 'Mangalvar', 'Budhvar', 'Guruvar', 'Shukravar', 'Shanivar'];
const WEEKDAY_ALIASES = {
  Sunday: ['ravivar', 'robibar', 'रविवार'],
  Monday: ['somvar', 'sombar', 'सोमवार'],
  Tuesday: ['mangalvar', 'मंगलवार'],
  Wednesday: ['budhvar', 'बुधवार'],
  Thursday: ['guruvar', 'गुरुवार'],
  Friday: ['shukravar', 'shukkar', 'शुक्रवार', 'friday'],
  Saturday: ['shanivar', 'शनिवार'],
};

/** Cultural packs — teach items + distractors grounded in each state */
const STATES = {
  ml: {
    code: 'ml',
    name: 'Meghalaya',
    greeting: 'Khublei',
    languageCodes: ['en-IN', 'kha'],
    capital: 'Shillong',
    distractHometowns: ['Guwahati', 'Kohima', 'Imphal', 'Aizawl', 'Agartala'],
    // teach triad for registrationIds
    teach: [
      {
        id: 'jadoh',
        label: 'Jadoh',
        aliases: ['jadoh', 'rice meat', 'khasi rice'],
        caption: 'Khasi rice cooked with meat',
        teachPrompt: 'This is Jadoh — Meghalaya rice with meat. Say Jadoh.',
        spoken: 'This is Jadoh. Say Jadoh with me.',
        quizPrompt: 'What rice dish did we learn?',
      },
      {
        id: 'living_root',
        label: 'Living root bridge',
        aliases: ['living root bridge', 'root bridge', 'jingkieng jri', 'bridge'],
        caption: 'Living root bridges of Meghalaya',
        teachPrompt: 'This is a living root bridge. Say living root bridge.',
        spoken: 'Living root bridge. Say living root bridge.',
        quizPrompt: 'Which bridge did we name?',
      },
      {
        id: 'wangala',
        label: 'Wangala',
        aliases: ['wangala', 'garo festival', '100 drums'],
        caption: 'Garo harvest festival',
        teachPrompt: 'This is Wangala — the Garo festival. Say Wangala.',
        spoken: 'This is Wangala. Say Wangala.',
        quizPrompt: 'Which festival did we remember?',
      },
    ],
    dress: {
      id: 'jainsem',
      label: 'Jainsem',
      aliases: ['jainsem', 'khasi dress', 'dress'],
      caption: 'Traditional Khasi jainsem',
      teachPrompt: 'This is Jainsem — Khasi traditional dress. Say Jainsem.',
      spoken: 'This is Jainsem. Say Jainsem with me.',
      quizPrompt: 'What is this Khasi dress called?',
      chips: ['Jainsem', 'Jadoh', 'Wangala', 'Book'],
    },
    cloth: {
      id: 'ryndia',
      label: 'Ryndia',
      aliases: ['ryndia', 'eri silk', 'silk'],
      caption: 'Meghalaya eri silk cloth',
      teachPrompt: 'This is Ryndia — soft eri silk. Say Ryndia.',
      spoken: 'This is Ryndia. Say Ryndia with me.',
      quizPrompt: 'What do we call this eri silk cloth?',
      chips: ['Ryndia', 'Jadoh', 'Wangala', 'Bicycle'],
    },
    landmark: 'living_root',
    festival: 'wangala',
    food: 'jadoh',
    rhythmName: 'Wangala drums',
    rhythmBeats: 3,
    teaName: 'Shillong tea',
    storyFood: 'jadoh',
    storyPlace: 'market in Shillong',
    eveningOdd: ['Jadoh', 'Wangala', 'Ryndia', 'Bicycle'],
    oddAnswer: ['bicycle', 'cycle', 'bike'],
    patternAsk: 'Which belongs with Meghalaya dress — jainsem or bicycle?',
    patternAns: ['jainsem', 'dress'],
    patternChips: ['Jainsem', 'Bicycle', 'Book', 'Clock'],
    sceneItems: ['rice', 'jadoh', 'jainsem', 'tea_cup', 'ryndia'],
    extraItems: {
      rice: { id: 'rice', label: 'Rice', aliases: ['rice'], caption: 'Steamed rice', image: 'rice.jpg' },
      tea_cup: { id: 'tea_cup', label: 'Tea cup', aliases: ['tea cup', 'cup', 'tea', 'chai'], caption: 'A cup of tea', image: 'tea_cup.jpg' },
      bicycle: { id: 'bicycle', label: 'Bicycle', aliases: ['bicycle', 'cycle', 'bike'], caption: 'A bicycle', image: 'bicycle.jpg' },
      book: { id: 'book', label: 'Book', aliases: ['book'], caption: 'A book', image: 'book.jpg' },
      home: { id: 'home', label: 'Home', aliases: ['home', 'house'], caption: 'Home in Meghalaya', image: 'home.jpg' },
      morning: { id: 'morning', label: 'Morning', aliases: ['morning'], caption: 'Morning in the hills', image: 'morning.jpg' },
      evening: { id: 'evening', label: 'Evening', aliases: ['evening'], caption: 'Evening in Shillong', image: 'evening.jpg' },
      shillong: { id: 'shillong', label: 'Shillong', aliases: ['shillong', 'capital'], caption: 'Capital of Meghalaya', image: 'shillong.jpg' },
      waterfall: { id: 'waterfall', label: 'Nohkalikai', aliases: ['nohkalikai', 'waterfall', 'falls'], caption: 'Nohkalikai Falls', image: 'waterfall.jpg' },
    },
  },

  mn: {
    code: 'mn',
    name: 'Manipur',
    greeting: 'Khurumjari',
    languageCodes: ['mni-IN', 'en-IN'],
    capital: 'Imphal',
    distractHometowns: ['Guwahati', 'Shillong', 'Kohima', 'Aizawl', 'Agartala'],
    teach: [
      {
        id: 'eromba',
        label: 'Eromba',
        aliases: ['eromba', 'mashed vegetables', 'manipuri dish'],
        caption: 'Manipuri mashed vegetables with fish',
        teachPrompt: 'This is Eromba — a Manipuri dish. Say Eromba.',
        spoken: 'This is Eromba. Say Eromba with me.',
        quizPrompt: 'What dish did we learn?',
      },
      {
        id: 'loktak',
        label: 'Loktak',
        aliases: ['loktak', 'loktak lake', 'floating lake', 'lake'],
        caption: 'Loktak Lake — floating phumdis',
        teachPrompt: 'This is Loktak Lake. Say Loktak.',
        spoken: 'This is Loktak. Say Loktak.',
        quizPrompt: 'Which lake did we name?',
      },
      {
        id: 'yaoshang',
        label: 'Yaoshang',
        aliases: ['yaoshang', 'holi', 'manipur festival'],
        caption: 'Manipur’s spring festival',
        teachPrompt: 'This is Yaoshang — Manipur’s festival. Say Yaoshang.',
        spoken: 'This is Yaoshang. Say Yaoshang.',
        quizPrompt: 'Which festival did we remember?',
      },
    ],
    dress: {
      id: 'phanek',
      label: 'Phanek',
      aliases: ['phanek', 'manipuri wrap', 'sarong'],
      caption: 'Traditional Manipuri phanek',
      teachPrompt: 'This is Phanek — Manipuri wrap dress. Say Phanek.',
      spoken: 'This is Phanek. Say Phanek with me.',
      quizPrompt: 'What is this Manipuri wrap called?',
      chips: ['Phanek', 'Eromba', 'Yaoshang', 'Book'],
    },
    cloth: {
      id: 'innaphi',
      label: 'Innaphi',
      aliases: ['innaphi', 'shawl', 'manipuri shawl'],
      caption: 'Manipuri innaphi shawl',
      teachPrompt: 'This is Innaphi — a soft Manipuri shawl. Say Innaphi.',
      spoken: 'This is Innaphi. Say Innaphi with me.',
      quizPrompt: 'What do we call this Manipuri shawl?',
      chips: ['Innaphi', 'Eromba', 'Loktak', 'Bicycle'],
    },
    landmark: 'loktak',
    festival: 'yaoshang',
    food: 'eromba',
    rhythmName: 'Pung drum',
    rhythmBeats: 3,
    teaName: 'evening tea',
    storyFood: 'eromba',
    storyPlace: 'Ima market',
    eveningOdd: ['Eromba', 'Yaoshang', 'Innaphi', 'Bicycle'],
    oddAnswer: ['bicycle', 'cycle', 'bike'],
    patternAsk: 'Which belongs with Manipur dress — phanek or bicycle?',
    patternAns: ['phanek'],
    patternChips: ['Phanek', 'Bicycle', 'Book', 'Clock'],
    sceneItems: ['rice', 'eromba', 'phanek', 'tea_cup', 'innaphi'],
    extraItems: {
      rice: { id: 'rice', label: 'Rice', aliases: ['rice'], caption: 'Steamed rice', image: 'rice.jpg' },
      tea_cup: { id: 'tea_cup', label: 'Tea cup', aliases: ['tea cup', 'cup', 'tea', 'chai'], caption: 'A cup of tea', image: 'tea_cup.jpg' },
      bicycle: { id: 'bicycle', label: 'Bicycle', aliases: ['bicycle', 'cycle', 'bike'], caption: 'A bicycle', image: 'bicycle.jpg' },
      book: { id: 'book', label: 'Book', aliases: ['book'], caption: 'A book', image: 'book.jpg' },
      home: { id: 'home', label: 'Home', aliases: ['home', 'house'], caption: 'Home in Manipur', image: 'home.jpg' },
      morning: { id: 'morning', label: 'Morning', aliases: ['morning'], caption: 'Morning in Imphal', image: 'morning.jpg' },
      evening: { id: 'evening', label: 'Evening', aliases: ['evening'], caption: 'Evening by Loktak', image: 'evening.jpg' },
      sangai: { id: 'sangai', label: 'Sangai', aliases: ['sangai', 'deer', 'brow antlered'], caption: 'Sangai — Manipur’s dancing deer', image: 'sangai.jpg' },
    },
  },

  nl: {
    code: 'nl',
    name: 'Nagaland',
    greeting: 'Welcome',
    languageCodes: ['en-IN'],
    capital: 'Kohima',
    distractHometowns: ['Guwahati', 'Shillong', 'Imphal', 'Aizawl', 'Itanagar'],
    teach: [
      {
        id: 'smoked_pork',
        label: 'Smoked pork',
        aliases: ['smoked pork', 'pork', 'bamboo shoot pork', 'naga pork'],
        caption: 'Naga smoked pork with bamboo shoot',
        teachPrompt: 'This is smoked pork — a Naga favourite. Say smoked pork.',
        spoken: 'Smoked pork. Say smoked pork with me.',
        quizPrompt: 'What dish did we learn?',
      },
      {
        id: 'dzukou',
        label: 'Dzukou',
        aliases: ['dzukou', 'dzuko', 'valley', 'dzukou valley'],
        caption: 'Dzukou Valley',
        teachPrompt: 'This is Dzukou Valley. Say Dzukou.',
        spoken: 'This is Dzukou. Say Dzukou.',
        quizPrompt: 'Which valley did we name?',
      },
      {
        id: 'hornbill',
        label: 'Hornbill',
        aliases: ['hornbill', 'hornbill festival', 'festival'],
        caption: 'Hornbill Festival of Nagaland',
        teachPrompt: 'This is Hornbill — Nagaland’s festival. Say Hornbill.',
        spoken: 'This is Hornbill. Say Hornbill.',
        quizPrompt: 'Which festival did we remember?',
      },
    ],
    dress: {
      id: 'naga_shawl',
      label: 'Naga shawl',
      aliases: ['naga shawl', 'shawl', 'tribal shawl'],
      caption: 'Colourful Naga tribal shawl',
      teachPrompt: 'This is a Naga shawl. Say Naga shawl.',
      spoken: 'Naga shawl. Say Naga shawl with me.',
      quizPrompt: 'What is this tribal wrap called?',
      chips: ['Naga shawl', 'Hornbill', 'Smoked pork', 'Book'],
    },
    cloth: {
      id: 'tribal_beads',
      label: 'Naga beads',
      aliases: ['naga beads', 'beads', 'necklace', 'tribal beads'],
      caption: 'Traditional Naga bead necklace',
      teachPrompt: 'These are Naga beads. Say Naga beads.',
      spoken: 'Naga beads. Say Naga beads with me.',
      quizPrompt: 'What jewellery did we name?',
      chips: ['Naga beads', 'Hornbill', 'Dzukou', 'Bicycle'],
    },
    landmark: 'dzukou',
    festival: 'hornbill',
    food: 'smoked_pork',
    rhythmName: 'Hornbill drums',
    rhythmBeats: 3,
    teaName: 'black tea',
    storyFood: 'smoked pork',
    storyPlace: 'Kohima market',
    eveningOdd: ['Hornbill', 'Naga beads', 'Naga shawl', 'Bicycle'],
    oddAnswer: ['bicycle', 'cycle', 'bike'],
    patternAsk: 'Which belongs with Naga dress — shawl or bicycle?',
    patternAns: ['shawl', 'naga shawl'],
    patternChips: ['Naga shawl', 'Bicycle', 'Book', 'Clock'],
    sceneItems: ['rice', 'smoked_pork', 'naga_shawl', 'tea_cup', 'tribal_beads'],
    extraItems: {
      rice: { id: 'rice', label: 'Rice', aliases: ['rice'], caption: 'Steamed rice', image: 'rice.jpg' },
      tea_cup: { id: 'tea_cup', label: 'Tea cup', aliases: ['tea cup', 'cup', 'tea', 'chai'], caption: 'A cup of tea', image: 'tea_cup.jpg' },
      bicycle: { id: 'bicycle', label: 'Bicycle', aliases: ['bicycle', 'cycle', 'bike'], caption: 'A bicycle', image: 'bicycle.jpg' },
      book: { id: 'book', label: 'Book', aliases: ['book'], caption: 'A book', image: 'book.jpg' },
      home: { id: 'home', label: 'Home', aliases: ['home', 'house'], caption: 'Home in Nagaland', image: 'home.jpg' },
      morning: { id: 'morning', label: 'Morning', aliases: ['morning'], caption: 'Morning in the hills', image: 'morning.jpg' },
      evening: { id: 'evening', label: 'Evening', aliases: ['evening'], caption: 'Evening in Kohima', image: 'evening.jpg' },
      moatsu: { id: 'moatsu', label: 'Moatsu', aliases: ['moatsu', 'ao festival'], caption: 'Moatsu festival of the Ao', image: 'moatsu.jpg' },
    },
  },

  mz: {
    code: 'mz',
    name: 'Mizoram',
    greeting: 'Chibai',
    languageCodes: ['en-IN'],
    capital: 'Aizawl',
    distractHometowns: ['Guwahati', 'Shillong', 'Imphal', 'Kohima', 'Agartala'],
    teach: [
      {
        id: 'bai',
        label: 'Bai',
        aliases: ['bai', 'boiled vegetables', 'mizo bai'],
        caption: 'Mizo bai — boiled vegetables with meat',
        teachPrompt: 'This is Bai — a Mizo dish. Say Bai.',
        spoken: 'This is Bai. Say Bai with me.',
        quizPrompt: 'What dish did we learn?',
      },
      {
        id: 'phawngpui',
        label: 'Phawngpui',
        aliases: ['phawngpui', 'blue mountain', 'mountain'],
        caption: 'Phawngpui — Blue Mountain',
        teachPrompt: 'This is Phawngpui — the Blue Mountain. Say Phawngpui.',
        spoken: 'This is Phawngpui. Say Phawngpui.',
        quizPrompt: 'Which mountain did we name?',
      },
      {
        id: 'chapchar_kut',
        label: 'Chapchar Kut',
        aliases: ['chapchar kut', 'chapchar', 'kut', 'mizo festival'],
        caption: 'Chapchar Kut — spring festival of Mizoram',
        teachPrompt: 'This is Chapchar Kut — Mizoram’s festival. Say Chapchar Kut.',
        spoken: 'Chapchar Kut. Say Chapchar Kut.',
        quizPrompt: 'Which festival did we remember?',
      },
    ],
    dress: {
      id: 'puan',
      label: 'Puan',
      aliases: ['puan', 'mizo puan', 'wrap'],
      caption: 'Traditional Mizo puan',
      teachPrompt: 'This is Puan — Mizo traditional wrap. Say Puan.',
      spoken: 'This is Puan. Say Puan with me.',
      quizPrompt: 'What is this Mizo wrap called?',
      chips: ['Puan', 'Bai', 'Chapchar Kut', 'Book'],
    },
    cloth: {
      id: 'hnipui',
      label: 'Hnipui',
      aliases: ['hnipui', 'shawl', 'mizo shawl'],
      caption: 'Mizo hnipui cloth',
      teachPrompt: 'This is Hnipui cloth. Say Hnipui.',
      spoken: 'This is Hnipui. Say Hnipui with me.',
      quizPrompt: 'What do we call this Mizo cloth?',
      chips: ['Hnipui', 'Bai', 'Phawngpui', 'Bicycle'],
    },
    landmark: 'phawngpui',
    festival: 'chapchar_kut',
    food: 'bai',
    rhythmName: 'Khuang drum',
    rhythmBeats: 3,
    teaName: 'evening tea',
    storyFood: 'bai',
    storyPlace: 'Aizawl market',
    eveningOdd: ['Bai', 'Puan', 'Hnipui', 'Bicycle'],
    oddAnswer: ['bicycle', 'cycle', 'bike'],
    patternAsk: 'Which belongs with Mizo dress — puan or bicycle?',
    patternAns: ['puan'],
    patternChips: ['Puan', 'Bicycle', 'Book', 'Clock'],
    sceneItems: ['rice', 'bai', 'puan', 'tea_cup', 'hnipui'],
    extraItems: {
      rice: { id: 'rice', label: 'Rice', aliases: ['rice'], caption: 'Steamed rice', image: 'rice.jpg' },
      tea_cup: { id: 'tea_cup', label: 'Tea cup', aliases: ['tea cup', 'cup', 'tea', 'chai'], caption: 'A cup of tea', image: 'tea_cup.jpg' },
      bicycle: { id: 'bicycle', label: 'Bicycle', aliases: ['bicycle', 'cycle', 'bike'], caption: 'A bicycle', image: 'bicycle.jpg' },
      book: { id: 'book', label: 'Book', aliases: ['book'], caption: 'A book', image: 'book.jpg' },
      home: { id: 'home', label: 'Home', aliases: ['home', 'house'], caption: 'Home in Mizoram', image: 'home.jpg' },
      morning: { id: 'morning', label: 'Morning', aliases: ['morning'], caption: 'Morning in Aizawl', image: 'morning.jpg' },
      evening: { id: 'evening', label: 'Evening', aliases: ['evening'], caption: 'Evening in the hills', image: 'evening.jpg' },
      reiek: { id: 'reiek', label: 'Reiek', aliases: ['reiek', 'peak'], caption: 'Reiek Peak', image: 'reiek.jpg' },
    },
  },

  tr: {
    code: 'tr',
    name: 'Tripura',
    greeting: 'Namaskar',
    languageCodes: ['bn-IN', 'en-IN'],
    capital: 'Agartala',
    distractHometowns: ['Guwahati', 'Shillong', 'Imphal', 'Aizawl', 'Kohima'],
    teach: [
      {
        id: 'mui_borok',
        label: 'Mui borok',
        aliases: ['mui borok', 'borok food', 'tripuri food'],
        caption: 'Traditional Tripuri mui borok meal',
        teachPrompt: 'This is Mui borok — Tripuri food. Say Mui borok.',
        spoken: 'Mui borok. Say Mui borok with me.',
        quizPrompt: 'What meal did we learn?',
      },
      {
        id: 'neermahal',
        label: 'Neermahal',
        aliases: ['neermahal', 'water palace', 'palace'],
        caption: 'Neermahal — the water palace',
        teachPrompt: 'This is Neermahal — the water palace. Say Neermahal.',
        spoken: 'This is Neermahal. Say Neermahal.',
        quizPrompt: 'Which palace did we name?',
      },
      {
        id: 'kharchi',
        label: 'Kharchi',
        aliases: ['kharchi', 'kharchi puja', 'festival'],
        caption: 'Kharchi Puja of Tripura',
        teachPrompt: 'This is Kharchi — Tripura’s festival. Say Kharchi.',
        spoken: 'This is Kharchi. Say Kharchi.',
        quizPrompt: 'Which festival did we remember?',
      },
    ],
    dress: {
      id: 'risha',
      label: 'Risha',
      aliases: ['risha', 'tripuri wrap', 'shawl'],
      caption: 'Traditional Tripuri risha',
      teachPrompt: 'This is Risha — Tripuri wrap. Say Risha.',
      spoken: 'This is Risha. Say Risha with me.',
      quizPrompt: 'What is this Tripuri wrap called?',
      chips: ['Risha', 'Mui borok', 'Kharchi', 'Book'],
    },
    cloth: {
      id: 'pachra',
      label: 'Pachra',
      aliases: ['pachra', 'tripuri cloth'],
      caption: 'Tripuri pachra cloth',
      teachPrompt: 'This is Pachra cloth. Say Pachra.',
      spoken: 'This is Pachra. Say Pachra with me.',
      quizPrompt: 'What do we call this Tripuri cloth?',
      chips: ['Pachra', 'Neermahal', 'Kharchi', 'Bicycle'],
    },
    landmark: 'neermahal',
    festival: 'kharchi',
    food: 'mui_borok',
    rhythmName: 'festival drums',
    rhythmBeats: 3,
    teaName: 'evening tea',
    storyFood: 'mui borok',
    storyPlace: 'Agartala market',
    eveningOdd: ['Mui borok', 'Risha', 'Kharchi', 'Bicycle'],
    oddAnswer: ['bicycle', 'cycle', 'bike'],
    patternAsk: 'Which belongs with Tripura dress — risha or bicycle?',
    patternAns: ['risha'],
    patternChips: ['Risha', 'Bicycle', 'Book', 'Clock'],
    sceneItems: ['rice', 'mui_borok', 'risha', 'tea_cup', 'pachra'],
    extraItems: {
      rice: { id: 'rice', label: 'Rice', aliases: ['rice'], caption: 'Steamed rice', image: 'rice.jpg' },
      tea_cup: { id: 'tea_cup', label: 'Tea cup', aliases: ['tea cup', 'cup', 'tea', 'chai'], caption: 'A cup of tea', image: 'tea_cup.jpg' },
      bicycle: { id: 'bicycle', label: 'Bicycle', aliases: ['bicycle', 'cycle', 'bike'], caption: 'A bicycle', image: 'bicycle.jpg' },
      book: { id: 'book', label: 'Book', aliases: ['book'], caption: 'A book', image: 'book.jpg' },
      home: { id: 'home', label: 'Home', aliases: ['home', 'house'], caption: 'Home in Tripura', image: 'home.jpg' },
      morning: { id: 'morning', label: 'Morning', aliases: ['morning'], caption: 'Morning in Agartala', image: 'morning.jpg' },
      evening: { id: 'evening', label: 'Evening', aliases: ['evening'], caption: 'Evening by the lake', image: 'evening.jpg' },
      ujjayanta: { id: 'ujjayanta', label: 'Ujjayanta', aliases: ['ujjayanta', 'palace'], caption: 'Ujjayanta Palace', image: 'ujjayanta.jpg' },
    },
  },

  ar: {
    code: 'ar',
    name: 'Arunachal Pradesh',
    greeting: 'Jullay',
    languageCodes: ['en-IN'],
    capital: 'Itanagar',
    distractHometowns: ['Guwahati', 'Shillong', 'Kohima', 'Imphal', 'Aizawl'],
    teach: [
      {
        id: 'thukpa',
        label: 'Thukpa',
        aliases: ['thukpa', 'noodle soup', 'soup'],
        caption: 'Warm Himalayan thukpa',
        teachPrompt: 'This is Thukpa — noodle soup. Say Thukpa.',
        spoken: 'This is Thukpa. Say Thukpa with me.',
        quizPrompt: 'What soup did we learn?',
      },
      {
        id: 'tawang',
        label: 'Tawang',
        aliases: ['tawang', 'tawang monastery', 'monastery'],
        caption: 'Tawang Monastery',
        teachPrompt: 'This is Tawang Monastery. Say Tawang.',
        spoken: 'This is Tawang. Say Tawang.',
        quizPrompt: 'Which place did we name?',
      },
      {
        id: 'losar',
        label: 'Losar',
        aliases: ['losar', 'new year', 'festival'],
        caption: 'Losar — New Year festival',
        teachPrompt: 'This is Losar — New Year festival. Say Losar.',
        spoken: 'This is Losar. Say Losar.',
        quizPrompt: 'Which festival did we remember?',
      },
    ],
    dress: {
      id: 'gale',
      label: 'Gale',
      aliases: ['gale', 'apai', 'arunachal wrap'],
      caption: 'Traditional Arunachal gale wrap',
      teachPrompt: 'This is Gale — traditional wrap. Say Gale.',
      spoken: 'This is Gale. Say Gale with me.',
      quizPrompt: 'What is this traditional wrap called?',
      chips: ['Gale', 'Thukpa', 'Losar', 'Book'],
    },
    cloth: {
      id: 'shawl_ar',
      label: 'Tribal shawl',
      aliases: ['tribal shawl', 'shawl', 'wool shawl'],
      caption: 'Warm tribal shawl of Arunachal',
      teachPrompt: 'This is a tribal shawl. Say tribal shawl.',
      spoken: 'Tribal shawl. Say tribal shawl with me.',
      quizPrompt: 'What do we call this warm wrap?',
      chips: ['Tribal shawl', 'Tawang', 'Losar', 'Bicycle'],
    },
    landmark: 'tawang',
    festival: 'losar',
    food: 'thukpa',
    rhythmName: 'monastery drums',
    rhythmBeats: 3,
    teaName: 'butter tea',
    storyFood: 'thukpa',
    storyPlace: 'Itanagar market',
    eveningOdd: ['Thukpa', 'Losar', 'Gale', 'Bicycle'],
    oddAnswer: ['bicycle', 'cycle', 'bike'],
    patternAsk: 'Which belongs with Arunachal dress — gale or bicycle?',
    patternAns: ['gale'],
    patternChips: ['Gale', 'Bicycle', 'Book', 'Clock'],
    sceneItems: ['rice', 'thukpa', 'gale', 'tea_cup', 'shawl_ar'],
    extraItems: {
      rice: { id: 'rice', label: 'Rice', aliases: ['rice'], caption: 'Steamed rice', image: 'rice.jpg' },
      tea_cup: { id: 'tea_cup', label: 'Tea cup', aliases: ['tea cup', 'cup', 'tea', 'butter tea'], caption: 'A cup of tea', image: 'tea_cup.jpg' },
      bicycle: { id: 'bicycle', label: 'Bicycle', aliases: ['bicycle', 'cycle', 'bike'], caption: 'A bicycle', image: 'bicycle.jpg' },
      book: { id: 'book', label: 'Book', aliases: ['book'], caption: 'A book', image: 'book.jpg' },
      home: { id: 'home', label: 'Home', aliases: ['home', 'house'], caption: 'Home in Arunachal', image: 'home.jpg' },
      morning: { id: 'morning', label: 'Morning', aliases: ['morning'], caption: 'Morning in the hills', image: 'morning.jpg' },
      evening: { id: 'evening', label: 'Evening', aliases: ['evening'], caption: 'Evening near Tawang', image: 'evening.jpg' },
      ziro: { id: 'ziro', label: 'Ziro', aliases: ['ziro', 'ziro valley'], caption: 'Ziro Valley', image: 'ziro.jpg' },
    },
  },
};

function buildBank(S) {
  const items = { ...S.extraItems };
  for (const t of S.teach) {
    items[t.id] = {
      id: t.id,
      label: t.label,
      aliases: t.aliases,
      caption: t.caption,
      image: `${t.id}.jpg`,
    };
  }
  items[S.dress.id] = {
    id: S.dress.id,
    label: S.dress.label,
    aliases: S.dress.aliases,
    caption: S.dress.caption,
    image: `${S.dress.id}.jpg`,
  };
  items[S.cloth.id] = {
    id: S.cloth.id,
    label: S.cloth.label,
    aliases: S.cloth.aliases,
    caption: S.cloth.caption,
    image: `${S.cloth.id}.jpg`,
  };

  return {
    state: S.code,
    name: S.name,
    greeting: S.greeting,
    languageCodes: S.languageCodes,
    imageBase: `/assets/curriculum/${S.code}`,
    weekdayNames: { en: WEEKDAY_EN, hi: WEEKDAY_HI },
    weekdayAliases: WEEKDAY_ALIASES,
    items,
    distractHometowns: S.distractHometowns,
  };
}

function morningPlan(S) {
  const [a, b, c] = S.teach;
  const d = S.dress;
  return {
    day: 1,
    sessionType: 'morning',
    theme: `{{preferredName}}’s morning with family`,
    title: `${S.name} morning — teach, then play`,
    clinicalFramework: 'DSM-5-TR Major/Mild Neurocognitive Disorder domains',
    registrationIds: [a.id, b.id, c.id],
    steps: [
      {
        id: 'm1-welcome',
        itemType: 'story_beat',
        domain: 'story',
        promptText: `${S.greeting}, {{preferredName}}. First we learn together — then we play.`,
        spokenPrompt: `${S.greeting}, {{preferredName}}. First we learn together, then we play. Ready?`,
        continueLabel: 'I’m ready',
        continueKicker: 'Teach first',
        autoCorrect: true,
        media: { kind: 'image', image: 'morning.jpg', caption: `${S.name} morning` },
      },
      {
        id: 'm1-teach-family-0',
        itemType: 'registration_teach',
        domain: 'learning_memory',
        promptText: 'This is {{family0.label}}. Look carefully. Remember their face.',
        spokenPrompt: 'This is {{family0.label}}. Look carefully. Say {{family0.label}} with me.',
        continueLabel: 'Next',
        continueKicker: 'Meet your family',
        autoCorrect: true,
        media: { kind: 'family', index: 0 },
      },
      {
        id: 'm1-teach-family-1',
        itemType: 'registration_teach',
        domain: 'learning_memory',
        promptText: 'This is {{family1.label}}. Look carefully. Remember their face.',
        spokenPrompt: 'This is {{family1.label}}. Look carefully. Say {{family1.label}} with me.',
        continueLabel: 'Next',
        continueKicker: 'Meet your family',
        autoCorrect: true,
        media: { kind: 'family', index: 1 },
      },
      {
        id: 'm1-teach-dress',
        itemType: 'registration_teach',
        domain: 'language',
        bankItem: d.id,
        promptText: d.teachPrompt,
        spokenPrompt: d.spoken,
        continueLabel: 'Next',
        continueKicker: 'Learn the word',
        autoCorrect: true,
      },
      {
        id: 'm1-teach-food',
        itemType: 'registration_teach',
        domain: 'learning_memory',
        bankItem: a.id,
        promptText: a.teachPrompt,
        spokenPrompt: a.spoken,
        continueLabel: 'Next',
        autoCorrect: true,
      },
      {
        id: 'm1-teach-place',
        itemType: 'registration_teach',
        domain: 'learning_memory',
        bankItem: b.id,
        promptText: b.teachPrompt,
        spokenPrompt: b.spoken,
        continueLabel: 'Next',
        autoCorrect: true,
      },
      {
        id: 'm1-teach-fest',
        itemType: 'registration_teach',
        domain: 'learning_memory',
        bankItem: c.id,
        promptText: c.teachPrompt,
        spokenPrompt: c.spoken,
        continueLabel: 'Next',
        autoCorrect: true,
      },
      {
        id: 'm1-teach-done',
        itemType: 'story_beat',
        domain: 'story',
        promptText: 'Beautiful. Now let’s play — remember what we just learned.',
        spokenPrompt: 'Beautiful, {{preferredName}}. Now let’s play. Remember what we just learned.',
        continueLabel: 'Start games',
        continueKicker: 'Quiz time',
        autoCorrect: true,
        media: { kind: 'image', image: 'morning.jpg', caption: 'Ready to play' },
      },
      {
        id: 'm1-quiz-family-0',
        itemType: 'orientation',
        domain: 'learning_memory',
        promptText: 'Who is this?',
        spokenPrompt: 'Who is this? Say their name.',
        answerFrom: 'family0',
        chipPool: 'familyLabels',
        hintText: 'This is {{family0.label}}.',
        media: { kind: 'family', index: 0 },
      },
      {
        id: 'm1-quiz-family-1',
        itemType: 'orientation',
        domain: 'learning_memory',
        promptText: 'And who is this?',
        spokenPrompt: 'And who is this?',
        answerFrom: 'family1',
        chipPool: 'familyLabels',
        hintText: 'This is {{family1.label}}.',
        media: { kind: 'family', index: 1 },
      },
      {
        id: 'm1-quiz-dress',
        itemType: 'language',
        domain: 'language',
        promptText: d.quizPrompt,
        spokenPrompt: d.quizPrompt,
        bankItem: d.id,
        expectedAnswers: d.aliases,
        chipOptions: d.chips,
        hintText: d.label + '.',
      },
      {
        id: 'm1-quiz-rhythm',
        itemType: 'rhythm_count',
        domain: 'complex_attention',
        promptText: `${S.rhythmName}: how many beats — 3 or 4?`,
        spokenPrompt: `${S.rhythmName} — beat, beat, beat. How many? Say three or four.`,
        expectedAnswers: ['3', 'three', 'teen', '३'],
        chipOptions: ['3 beats', '4 beats', '2 beats', '5 beats'],
        hintText: 'Three beats.',
        media: { kind: 'image', image: `${S.festival || c.id}.jpg`, caption: S.rhythmName },
      },
      {
        id: 'm1-quiz-attn',
        itemType: 'attention_change',
        domain: 'complex_attention',
        promptText: 'What disappeared from the breakfast table?',
        spokenPrompt: 'Look at the table. Now look again. What disappeared?',
        expectedAnswers: ['tea cup', 'cup', 'tea', 'chai'],
        chipOptions: ['Tea cup', d.label, 'Rice', a.label],
        hintText: 'The tea cup is missing.',
        sceneBefore: S.sceneItems,
        sceneAfter: S.sceneItems.filter((x) => x !== 'tea_cup'),
        lookMs: 8000,
      },
      {
        id: 'm1-quiz-exec',
        itemType: 'sequence_order',
        domain: 'executive_function',
        promptText: `${S.teaName} — tap the steps in order.`,
        spokenPrompt: `Making ${S.teaName}. Tap in order — boil water, add leaves, pour, then sip.`,
        sequenceSteps: [
          { id: 'boil', label: '1. Boil water' },
          { id: 'leaves', label: '2. Add leaves' },
          { id: 'pour', label: '3. Pour into cup' },
          { id: 'sip', label: '4. Sip slowly' },
        ],
        expectedAnswers: ['boil leaves pour sip', '1 2 3 4'],
        hintText: 'Boil → leaves → pour → sip.',
        media: { kind: 'image', image: 'tea_cup.jpg', caption: S.teaName },
      },
      {
        id: 'm1-quiz-food',
        itemType: 'recall',
        domain: 'learning_memory',
        promptText: a.quizPrompt,
        spokenPrompt: a.quizPrompt,
        bankItem: a.id,
        chipPool: 'registrationSet',
        hintText: a.label + '.',
      },
      {
        id: 'm1-quiz-place',
        itemType: 'recall',
        domain: 'learning_memory',
        promptText: b.quizPrompt,
        spokenPrompt: b.quizPrompt,
        bankItem: b.id,
        chipPool: 'registrationSet',
        hintText: b.label + '.',
      },
      {
        id: 'm1-quiz-family-mid',
        itemType: 'orientation',
        domain: 'learning_memory',
        promptText: 'Look again — who is this?',
        spokenPrompt: 'Look again. Who is this?',
        answerFrom: 'family0',
        chipPool: 'familyLabels',
        hintText: 'This is {{family0.label}}.',
        media: { kind: 'family', index: 0 },
      },
      {
        id: 'm1-quiz-fest',
        itemType: 'recall',
        domain: 'learning_memory',
        promptText: c.quizPrompt,
        spokenPrompt: c.quizPrompt,
        bankItem: c.id,
        chipPool: 'registrationSet',
        hintText: c.label + '.',
      },
      {
        id: 'm1-quiz-pattern',
        itemType: 'pattern_match',
        domain: 'perceptual_motor',
        promptText: S.patternAsk,
        spokenPrompt: S.patternAsk,
        expectedAnswers: S.patternAns,
        chipOptions: S.patternChips,
        hintText: S.patternAns[0] + '.',
        media: { kind: 'image', image: `${d.id}.jpg`, caption: 'Pattern' },
      },
      {
        id: 'm1-quiz-emotion',
        itemType: 'emotion_quiz',
        domain: 'social_cognition',
        promptText: 'Look at {{family0.label}}. Happy or sad?',
        spokenPrompt: 'Look at {{family0.label}}. How do they feel — happy or sad?',
        expectedAnswers: ['happy', 'glad', 'smiling', 'joy', 'khush', 'खुश'],
        chipOptions: ['Happy', 'Sad', 'Angry', 'Afraid'],
        hintText: 'Happy.',
        media: { kind: 'family', index: 0 },
      },
      {
        id: 'm1-story-setup',
        itemType: 'story_beat',
        domain: 'story',
        promptText: `Family story: morning with {{family0.label}} and ${S.storyFood}.`,
        spokenPrompt: `Family story. {{family0.label}} made ${S.storyFood}. Let’s begin.`,
        continueLabel: 'Start story',
        continueKicker: 'Reminiscence',
        autoCorrect: true,
        media: { kind: 'family', index: 0 },
      },
      {
        id: 'm1-story-who',
        itemType: 'story_quiz',
        domain: 'language',
        promptText: `Who made ${S.storyFood} with you?`,
        spokenPrompt: `Who made ${S.storyFood} with you?`,
        answerFrom: 'family0',
        chipPool: 'familyLabels',
        hintText: '{{family0.label}}.',
        media: { kind: 'family', index: 0 },
      },
      {
        id: 'm1-story-who-2',
        itemType: 'story_quiz',
        domain: 'learning_memory',
        promptText: `{{family1.label}} went to ${S.storyPlace}. Who went?`,
        spokenPrompt: `{{family1.label}} went to ${S.storyPlace}. Who went?`,
        answerFrom: 'family1',
        chipPool: 'familyLabels',
        hintText: '{{family1.label}}.',
        media: { kind: 'family', index: 1 },
      },
      {
        id: 'm1-finale',
        itemType: 'story_beat',
        domain: 'story',
        promptText: 'Wonderful, {{preferredName}}. {{family0.label}} is proud of you.',
        spokenPrompt: 'Wonderful, {{preferredName}}. {{family0.label}} is proud of you. See you this evening.',
        continueLabel: 'Finish',
        continueKicker: 'Morning done',
        autoCorrect: true,
        media: { kind: 'family', index: 0 },
      },
    ],
  };
}

function eveningPlan(S) {
  const [a, b, c] = S.teach;
  const cl = S.cloth;
  return {
    day: 1,
    sessionType: 'evening',
    theme: `{{preferredName}}’s evening with family`,
    title: `${S.name} evening — teach, then play`,
    clinicalFramework: 'DSM-5-TR Major/Mild Neurocognitive Disorder domains',
    registrationIds: [a.id, b.id, c.id],
    steps: [
      {
        id: 'e1-welcome',
        itemType: 'story_beat',
        domain: 'story',
        promptText: `Good evening, {{preferredName}}. First a gentle reminder — then games.`,
        spokenPrompt: `Good evening, {{preferredName}}. First a gentle reminder of today’s words, then games. Ready?`,
        continueLabel: 'I’m ready',
        continueKicker: 'Teach first',
        autoCorrect: true,
        media: { kind: 'image', image: 'evening.jpg', caption: `${S.name} evening` },
      },
      {
        id: 'e1-teach-family-0',
        itemType: 'registration_teach',
        domain: 'learning_memory',
        promptText: 'This is {{family0.label}}. Look again. Remember.',
        spokenPrompt: 'This is {{family0.label}}. Look again. Say {{family0.label}}.',
        continueLabel: 'Next',
        continueKicker: 'Family reminder',
        autoCorrect: true,
        media: { kind: 'family', index: 0 },
      },
      {
        id: 'e1-teach-family-1',
        itemType: 'registration_teach',
        domain: 'learning_memory',
        promptText: 'This is {{family1.label}}. Look carefully.',
        spokenPrompt: 'This is {{family1.label}}. Say {{family1.label}}.',
        continueLabel: 'Next',
        continueKicker: 'Family reminder',
        autoCorrect: true,
        media: { kind: 'family', index: 1 },
      },
      {
        id: 'e1-teach-food',
        itemType: 'registration_teach',
        domain: 'learning_memory',
        bankItem: a.id,
        promptText: `From this morning — ${a.label}. Say ${a.label}.`,
        spokenPrompt: `From this morning — ${a.label}. Say ${a.label}.`,
        continueLabel: 'Next',
        autoCorrect: true,
      },
      {
        id: 'e1-teach-place',
        itemType: 'registration_teach',
        domain: 'learning_memory',
        bankItem: b.id,
        promptText: `${b.label}. Say ${b.label}.`,
        spokenPrompt: `${b.label}. Say ${b.label}.`,
        continueLabel: 'Next',
        autoCorrect: true,
      },
      {
        id: 'e1-teach-fest',
        itemType: 'registration_teach',
        domain: 'learning_memory',
        bankItem: c.id,
        promptText: `${c.label} — our festival. Say ${c.label}.`,
        spokenPrompt: `${c.label}. Say ${c.label}.`,
        continueLabel: 'Next',
        autoCorrect: true,
      },
      {
        id: 'e1-teach-cloth',
        itemType: 'registration_teach',
        domain: 'language',
        bankItem: cl.id,
        promptText: cl.teachPrompt,
        spokenPrompt: cl.spoken,
        continueLabel: 'Next',
        continueKicker: 'Learn the word',
        autoCorrect: true,
      },
      {
        id: 'e1-teach-done',
        itemType: 'story_beat',
        domain: 'story',
        promptText: 'Good. Now evening games — use what we just reviewed.',
        spokenPrompt: 'Good, {{preferredName}}. Now evening games.',
        continueLabel: 'Start games',
        continueKicker: 'Quiz time',
        autoCorrect: true,
        media: { kind: 'image', image: 'evening.jpg', caption: 'Ready to play' },
      },
      {
        id: 'e1-quiz-family-0',
        itemType: 'orientation',
        domain: 'learning_memory',
        promptText: 'Who is this?',
        spokenPrompt: 'Who is this?',
        answerFrom: 'family0',
        chipPool: 'familyLabels',
        hintText: 'This is {{family0.label}}.',
        media: { kind: 'family', index: 0 },
      },
      {
        id: 'e1-quiz-family-1',
        itemType: 'orientation',
        domain: 'learning_memory',
        promptText: 'And who is this?',
        spokenPrompt: 'And who is this?',
        answerFrom: 'family1',
        chipPool: 'familyLabels',
        hintText: 'This is {{family1.label}}.',
        media: { kind: 'family', index: 1 },
      },
      {
        id: 'e1-quiz-fest',
        itemType: 'recall',
        domain: 'learning_memory',
        promptText: 'What festival did we name?',
        spokenPrompt: 'What festival did we name?',
        bankItem: c.id,
        chipPool: 'registrationSet',
        hintText: c.label + '.',
      },
      {
        id: 'e1-quiz-place',
        itemType: 'recall',
        domain: 'learning_memory',
        promptText: b.quizPrompt,
        spokenPrompt: b.quizPrompt,
        bankItem: b.id,
        chipPool: 'registrationSet',
        hintText: b.label + '.',
      },
      {
        id: 'e1-quiz-food',
        itemType: 'recall',
        domain: 'learning_memory',
        promptText: a.quizPrompt,
        spokenPrompt: a.quizPrompt,
        bankItem: a.id,
        chipPool: 'registrationSet',
        hintText: a.label + '.',
      },
      {
        id: 'e1-quiz-cloth',
        itemType: 'language',
        domain: 'language',
        promptText: cl.quizPrompt,
        spokenPrompt: cl.quizPrompt,
        bankItem: cl.id,
        expectedAnswers: cl.aliases,
        chipOptions: cl.chips,
        hintText: cl.label + '.',
      },
      {
        id: 'e1-quiz-attn',
        itemType: 'attention_change',
        domain: 'complex_attention',
        promptText: 'What is new on the evening table?',
        spokenPrompt: 'Look at the table. Now look again. What is new?',
        expectedAnswers: ['tea cup', 'cup', 'tea', 'chai'],
        chipOptions: ['Tea cup', a.label, cl.label, 'Book'],
        hintText: 'A tea cup appeared.',
        sceneBefore: S.sceneItems.filter((x) => x !== 'tea_cup'),
        sceneAfter: S.sceneItems,
        lookMs: 8000,
      },
      {
        id: 'e1-quiz-exec',
        itemType: 'sequence_order',
        domain: 'executive_function',
        promptText: 'Evening wind-down — tap steps in order.',
        spokenPrompt: 'Tap in order — wash hands, sit for tea, share a story, rest.',
        sequenceSteps: [
          { id: 'wash', label: '1. Wash hands' },
          { id: 'tea', label: '2. Sit for tea' },
          { id: 'story', label: '3. Share a story' },
          { id: 'rest', label: '4. Rest' },
        ],
        expectedAnswers: ['wash tea story rest'],
        hintText: 'Wash → tea → story → rest.',
        media: { kind: 'family', index: 0 },
      },
      {
        id: 'e1-quiz-family-mid',
        itemType: 'orientation',
        domain: 'learning_memory',
        promptText: 'Still with us — who is this?',
        spokenPrompt: 'Still with us. Who is this?',
        answerFrom: 'family1',
        chipPool: 'familyLabels',
        hintText: 'This is {{family1.label}}.',
        media: { kind: 'family', index: 1 },
      },
      {
        id: 'e1-quiz-pattern',
        itemType: 'pattern_match',
        domain: 'perceptual_motor',
        promptText: 'On the tray — which does not belong?',
        spokenPrompt: `${S.eveningOdd.join(', ')} — which does not belong?`,
        expectedAnswers: S.oddAnswer,
        chipOptions: S.eveningOdd,
        hintText: 'Bicycle.',
        media: { kind: 'image', image: 'bicycle.jpg', caption: 'Odd one out' },
      },
      {
        id: 'e1-quiz-emotion',
        itemType: 'emotion_quiz',
        domain: 'social_cognition',
        promptText: 'How might {{family0.label}} feel after calm tea?',
        spokenPrompt: 'How might {{family0.label}} feel — peaceful or angry?',
        expectedAnswers: ['peaceful', 'calm', 'happy', 'relaxed', 'content', 'shant'],
        chipOptions: ['Peaceful', 'Angry', 'Afraid', 'Confused'],
        hintText: 'Peaceful.',
        media: { kind: 'family', index: 0 },
      },
      {
        id: 'e1-quiz-rhythm',
        itemType: 'rhythm_count',
        domain: 'complex_attention',
        promptText: 'Soft claps: how many — 2 or 3?',
        spokenPrompt: 'Clap, clap. How many? Say two or three.',
        expectedAnswers: ['2', 'two', 'do', '२'],
        chipOptions: ['2 claps', '3 claps', '4 claps', '1 clap'],
        hintText: 'Two.',
        media: { kind: 'image', image: 'evening.jpg', caption: 'Soft rhythm' },
      },
      {
        id: 'e1-story-setup',
        itemType: 'story_beat',
        domain: 'story',
        promptText: `Family story: evening tea with {{family0.label}}.`,
        spokenPrompt: `You and {{family0.label}} sit for tea. {{family1.label}} brings ${S.storyFood}. Let’s begin.`,
        continueLabel: 'Start story',
        continueKicker: 'Reminiscence',
        autoCorrect: true,
        media: { kind: 'family', index: 0 },
      },
      {
        id: 'e1-story-who-1',
        itemType: 'story_quiz',
        domain: 'language',
        promptText: `Who brought the ${S.storyFood}?`,
        spokenPrompt: `Who brought the ${S.storyFood}?`,
        answerFrom: 'family1',
        chipPool: 'familyLabels',
        hintText: '{{family1.label}}.',
        media: { kind: 'family', index: 1 },
      },
      {
        id: 'e1-story-who-0',
        itemType: 'story_quiz',
        domain: 'learning_memory',
        promptText: 'Who sat with you for tea?',
        spokenPrompt: `Who sat with you for ${S.teaName}?`,
        answerFrom: 'family0',
        chipPool: 'familyLabels',
        hintText: '{{family0.label}}.',
        media: { kind: 'family', index: 0 },
      },
      {
        id: 'e1-finale',
        itemType: 'story_beat',
        domain: 'story',
        promptText: 'Rest well, {{preferredName}}. {{family0.label}} and {{family1.label}} love you.',
        spokenPrompt: 'Rest well, {{preferredName}}. {{family0.label}} and {{family1.label}} love you. Good night.',
        continueLabel: 'Finish',
        continueKicker: 'Evening done',
        autoCorrect: true,
        media: { kind: 'family', index: 0 },
      },
    ],
  };
}

function writePack(S) {
  const dir = path.join(ROOT, S.code);
  const days = path.join(dir, 'days');
  fs.mkdirSync(days, { recursive: true });
  const bank = buildBank(S);
  fs.writeFileSync(path.join(dir, 'bank.json'), JSON.stringify(bank, null, 2));
  fs.writeFileSync(path.join(days, 'day1.morning.json'), JSON.stringify(morningPlan(S), null, 2));
  fs.writeFileSync(path.join(days, 'day1.evening.json'), JSON.stringify(eveningPlan(S), null, 2));

  const pub = path.join(PUBLIC, S.code, 'days');
  fs.mkdirSync(pub, { recursive: true });
  fs.writeFileSync(path.join(PUBLIC, S.code, 'bank.json'), JSON.stringify(bank, null, 2));
  fs.writeFileSync(path.join(pub, 'day1.morning.json'), JSON.stringify(morningPlan(S), null, 2));
  fs.writeFileSync(path.join(pub, 'day1.evening.json'), JSON.stringify(eveningPlan(S), null, 2));
  console.log('OK', S.code, S.name);
}

for (const S of Object.values(STATES)) writePack(S);
console.log('Generated 6 NER packs (+ synced to public/). Assam (as) unchanged.');
